//! herdr-ddev: ddev status badges, start/stop/open actions and a project picker for Herdr.
pub mod actions;
pub mod app;
pub mod badge;
pub mod bins;
pub mod busy;
pub mod config;
pub mod configure;
pub mod ddev;
pub mod detach;
pub mod docker;
pub mod herdr;
pub mod lock;
pub mod open;
pub mod picker;
pub mod popup;
pub mod project;
pub mod runner;
pub mod ticker;
